### ISSUE TITLE
OSTicket v1.10 - Get this on a new email during cron job with no ticket created.

### ISSUE THREAD

**Issue by StealthMicro** [tuudik/osticket-rocketchat#4]
OSTicket v1.10 and I get the following error.

PHP Fatal error:  Uncaught Error: Call to a member function getLastMessage() on null in /var/www/clients/client3/web20/web/include/class.ticket.php:801
Stack trace:
#0 /var/www/clients/client3/web20/web/include/plugins/rocketchat/rocketchat.php(71): Ticket->getLastMessage()
#1 /var/www/clients/client3/web20/web/include/class.signal.php(98): RocketChatPlugin->onTicketCreated(Object(Ticket), NULL)
#2 /var/www/clients/client3/web20/web/include/class.orm.php(619): Signal::send('model.created', Object(Ticket))
#3 /var/www/clients/client3/web20/web/include/class.ticket.php(2740): VerySimpleModel->save(true)
#4 /var/www/clients/client3/web20/web/include/class.ticket.php(3373): Ticket->save()
#5 /var/www/clients/client3/web20/web/include/class.mailfetch.php(796): Ticket::create(Array, Array, 'Email')
#6 /var/www/clients/client3/web20/web/include/class.mailfetch.php(845): MailFetcher->createTicket(1)
#7 /var/www/clients/client3/web20/web/include/class.mailfetch.php(925): MailFetcher->fetchEmails()
#8 /var/www/clients/client3/web20/web/ in /var/www/clients/client3/web20/web/include/class.ticket.php on line 801

**Comment by jpdentone** [comment]
Im getting the same... 

`[Wed Jul 05 20:32:22.980353 2017] [:error] [pid 2909] [client 172.38.10.6:62805] PHP Fatal error:  Uncaught Error: Call to a member function getLastMessage() on null in /var/www/html/osticket/upload/include/class.ticket.php:801\nStack trace:\n#0 /var/www/html/osticket/upload/include/plugins/rocketchat/rocketchat.php(71): Ticket->getLastMessage()\n#1 /var/www/html/osticket/upload/include/class.signal.php(98): RocketChatPlugin->onTicketCreated(Object(Ticket), NULL)\n#2 /var/www/html/osticket/upload/include/class.orm.php(619): Signal::send('model.created', Object(Ticket))\n#3 /var/www/html/osticket/upload/include/class.ticket.php(2740): VerySimpleModel->save(true)\n#4 /var/www/html/osticket/upload/include/class.ticket.php(3373): Ticket->save()\n#5 /var/www/html/osticket/upload/open.php(42): Ticket::create(Array, Array, 'Web')\n#6 {main}\n  thrown in /var/www/html/osticket/upload/include/class.ticket.php on line 801`

osTicket Version	v1.10 (901e5ea)

any workaround for this?

**Comment by tuudik** [comment]
I am sorry, but I dont have any time for now to maintain this plugin/repostiory. Neither do I have any running osTicket instances.
