### ISSUE TITLE
Pluging makes osticket crash on new ticket

### ISSUE THREAD

**Issue by jpdentone** [tuudik/osticket-rocketchat#5]
Whenever I want to open a new ticket... it never sends... I get a blank page and this on the logs

`[Wed Jul 05 20:32:22.980353 2017] [:error] [pid 2909] [client 172.38.10.6:62805] PHP Fatal error:  Uncaught Error: Call to a member function getLastMessage() on null in /var/www/html/osticket/upload/include/class.ticket.php:801\nStack trace:\n#0 /var/www/html/osticket/upload/include/plugins/rocketchat/rocketchat.php(71): Ticket->getLastMessage()\n#1 /var/www/html/osticket/upload/include/class.signal.php(98): RocketChatPlugin->onTicketCreated(Object(Ticket), NULL)\n#2 /var/www/html/osticket/upload/include/class.orm.php(619): Signal::send('model.created', Object(Ticket))\n#3 /var/www/html/osticket/upload/include/class.ticket.php(2740): VerySimpleModel->save(true)\n#4 /var/www/html/osticket/upload/include/class.ticket.php(3373): Ticket->save()\n#5 /var/www/html/osticket/upload/open.php(42): Ticket::create(Array, Array, 'Web')\n#6 {main}\n  thrown in /var/www/html/osticket/upload/include/class.ticket.php on line 801`

osTicket Version	v1.10 (901e5ea)

any workaround for this?

**Comment by tuudik** [comment]
I am sorry, but I dont have any time for now to maintain this plugin/repostiory. Neither do I have any running osTicket instances.

**Comment by MikeColes** [comment]
For others that have the same issue, I found that this plugin can be modified fairly easily. I'm using it as a base for Zulip pushes.  
https://github.com/deaconw/osticket-pushover-plugin
